/* Platform Ontology Browser — no dependencies, no build step.
   All content comes from data/index.json, generated by ci/build_index.py
   from the Turtle sources, so the browser cannot drift from the ontology. */

(() => {
  "use strict";

  let DB = null;
  const byCurie = new Map();
  const decById = new Map();
  let searchDocs = [];

  /* ---------- helpers ---------- */
  const $ = (sel, root = document) => root.querySelector(sel);
  const esc = (s) => String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  const modClass = (m) => (m || "core").replace(/[^a-z-]/g, "");
  const kindLabel = { class: "Class", objectProperty: "Object property", datatypeProperty: "Datatype property" };
  const termHref = (curie) => `#/term/${encodeURIComponent(curie)}`;

  function link(curie, extra = "") {
    if (!curie) return "";
    if (byCurie.has(curie)) {
      return `<a class="mono" href="${termHref(curie)}"${extra}>${esc(curie)}</a>`;
    }
    return `<code>${esc(curie)}</code>`;
  }

  function tag(mod) {
    return mod ? `<span class="tag ${modClass(mod)}">${esc(mod)}</span>` : "";
  }

  function sevPill(sev) {
    const s = (sev || "Violation").toLowerCase();
    return `<span class="pill ${s === "warning" ? "warning" : "violation"}">${esc(sev || "Violation")}</span>`;
  }

  /* ---------- search ---------- */
  function buildSearchDocs() {
    const docs = [];
    for (const t of DB.terms) {
      docs.push({
        type: "term", kind: kindLabel[t.kind] || t.kind, module: t.module,
        title: t.curie, sub: t.definition || t.label || "",
        href: termHref(t.curie),
        hay: [t.curie, t.name, t.label, t.definition, t.editorialNote, ...(t.altLabels || [])]
          .filter(Boolean).join(" ").toLowerCase(),
        boost: t.kind === "class" ? 3 : 1,
      });
    }
    for (const s of DB.shapes) {
      const msgs = s.constraints.map((c) => c.message).filter(Boolean).join(" ");
      docs.push({
        type: "shape", kind: "Constraint", module: s.module,
        title: s.name, sub: s.constraints.find((c) => c.message)?.message || "",
        href: `#/shapes?q=${encodeURIComponent(s.name)}`,
        hay: [s.name, s.targetClass, msgs].filter(Boolean).join(" ").toLowerCase(),
        boost: 1,
      });
    }
    for (const d of DB.decisions) {
      docs.push({
        type: "decision", kind: "Decision", module: null,
        title: `${d.id} · ${d.title}`, sub: d.reasoning,
        href: `#/decisions?q=${encodeURIComponent(d.id)}`,
        hay: [d.id, d.title, d.reasoning, d.area, (d.rejected || []).join(" ")]
          .filter(Boolean).join(" ").toLowerCase(),
        boost: 2,
      });
    }
    const cq = DB.competencyQuestions;
    for (const q of cq.formal) {
      docs.push({
        type: "question", kind: q.id, module: null, title: q.question, sub: q.query,
        href: `#/questions?q=${encodeURIComponent(q.id)}`,
        hay: [q.id, q.question, q.query].join(" ").toLowerCase(), boost: 1,
      });
    }
    for (const q of cq.backlog) {
      docs.push({
        type: "question", kind: "Backlog", module: null, title: q.question, sub: q.section,
        href: `#/questions?q=${encodeURIComponent(q.question.slice(0, 40))}`,
        hay: [q.question, q.section].join(" ").toLowerCase(), boost: 0.5,
      });
    }
    searchDocs = docs;
  }

  function search(query, limit = 24) {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    const tokens = q.split(/\s+/).filter(Boolean);
    const out = [];
    for (const d of searchDocs) {
      let score = 0, ok = true;
      for (const tk of tokens) {
        const i = d.hay.indexOf(tk);
        if (i === -1) { ok = false; break; }
        score += 10;
        const title = d.title.toLowerCase();
        if (title.includes(tk)) score += 25;
        if (title.startsWith(tk)) score += 30;
        const afterColon = title.split(":").pop();
        if (afterColon && afterColon.startsWith(tk)) score += 20;
        if (i < 60) score += 5;
      }
      if (!ok) continue;
      out.push({ doc: d, score: score * (1 + (d.boost || 0) / 4) });
    }
    out.sort((a, b) => b.score - a.score || a.doc.title.length - b.doc.title.length);
    return out.slice(0, limit).map((x) => x.doc);
  }

  function highlight(text, query) {
    const t = String(text || "");
    const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
    if (!tokens.length) return esc(t);
    const re = new RegExp("(" + tokens.map((x) => x.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|") + ")", "gi");
    return esc(t).replace(re, "<mark>$1</mark>");
  }

  function renderResults(query) {
    const box = $("#results");
    const hits = search(query);
    if (!query.trim()) { box.hidden = true; $("#search").setAttribute("aria-expanded", "false"); return; }
    if (!hits.length) {
      box.innerHTML = `<div class="empty">No matches for <b>${esc(query)}</b></div>`;
      box.hidden = false; return;
    }
    const groups = { term: [], shape: [], decision: [], question: [] };
    hits.forEach((h) => groups[h.type].push(h));
    const labels = { term: "Terms", shape: "Constraints", decision: "Decisions", question: "Questions" };
    let html = "";
    for (const key of ["term", "shape", "decision", "question"]) {
      if (!groups[key].length) continue;
      html += `<div class="rgroup">${labels[key]}</div>`;
      for (const d of groups[key]) {
        html += `<a href="${d.href}" role="option">
          <div class="rtitle"><b>${highlight(d.title, query)}</b>
            ${d.module ? tag(d.module) : ""}
            <span class="pill draft">${esc(d.kind)}</span></div>
          ${d.sub ? `<div class="rdesc">${highlight(d.sub, query)}</div>` : ""}
        </a>`;
      }
    }
    box.innerHTML = html;
    box.hidden = false;
    $("#search").setAttribute("aria-expanded", "true");
  }

  /* ---------- sidebar ---------- */
  let sideKind = "all";
  function renderTree() {
    const filter = $("#filter").value.trim().toLowerCase();
    const tree = $("#tree");
    let html = "";
    let total = 0;
    for (const m of DB.modules) {
      let items = DB.terms.filter((t) => t.module === m.name);
      if (sideKind !== "all") items = items.filter((t) => t.kind === sideKind);
      if (filter) {
        items = items.filter((t) =>
          t.curie.toLowerCase().includes(filter) ||
          (t.definition || "").toLowerCase().includes(filter));
      }
      if (!items.length) continue;
      total += items.length;
      const open = filter || items.length <= 40 ? "" : "";
      html += `<div class="mod ${open}" data-mod="${esc(m.name)}">
        <button class="modhead" type="button" aria-expanded="true">
          <span class="caret">▾</span>
          <span class="dot" style="background: var(--m-${modClass(m.name)})"></span>
          <span class="nm">${esc(m.name)}</span>
          <span class="ct">${items.length}</span>
        </button>
        <div class="items">
          <a href="#/module/${esc(m.name)}" data-curie="module:${esc(m.name)}"><span class="k">M</span>overview</a>
          ${items.map((t) => `<a href="${termHref(t.curie)}" data-curie="${esc(t.curie)}">
            <span class="k">${t.kind === "class" ? "C" : t.kind === "objectProperty" ? "O" : "D"}</span>
            ${esc(t.name)}</a>`).join("")}
        </div>
      </div>`;
    }
    tree.innerHTML = total ? html : `<div class="none">No terms match “${esc(filter)}”.</div>`;
    tree.querySelectorAll(".modhead").forEach((btn) => {
      btn.addEventListener("click", () => {
        const mod = btn.closest(".mod");
        mod.classList.toggle("closed");
        btn.setAttribute("aria-expanded", String(!mod.classList.contains("closed")));
      });
    });
    markActive();
  }

  function markActive() {
    const hash = location.hash;
    document.querySelectorAll(".tree .items a").forEach((a) => {
      a.classList.toggle("on", a.getAttribute("href") === hash);
    });
    document.querySelectorAll(".topnav a").forEach((a) => {
      a.classList.toggle("on", hash.startsWith(a.getAttribute("href")));
    });
  }

  /* ---------- views ---------- */
  function viewHome() {
    const s = DB.stats;
    const mods = DB.modules.map((m) => {
      const counts = DB.terms.filter((t) => t.module === m.name);
      const cls = counts.filter((t) => t.kind === "class").length;
      const props = counts.length - cls;
      const shapes = DB.shapes.filter((x) => x.module === m.name).length;
      return `<div class="card modcard">
        <div class="mh">${tag(m.name)}<span class="pill draft">v${esc(m.version)}</span></div>
        <p>${esc(m.blurb || m.description)}</p>
        <div class="counts">${cls} classes · ${props} properties · ${shapes} shapes${
          m.imports.length ? ` · imports ${m.imports.map(esc).join(", ")}` : ""}</div>
        <div><a href="#/module/${esc(m.name)}">Browse ${esc(m.name)} →</a></div>
      </div>`;
    }).join("");

    return `
      <div class="crumb">Platform identity &amp; access ontology · all terms draft</div>
      <h1 class="title">Ontology Browser</h1>
      <p class="lede">Every class, property, constraint and relationship in the platform
      ontology — and, for each one, the recorded reasoning for why it exists. Generated
      directly from the Turtle sources, so what you read here is what CI validates.</p>
      <div class="stats">
        <div><div class="n">${s.classes}</div><div class="l">Classes</div></div>
        <div><div class="n">${s.objectProperties + s.datatypeProperties}</div><div class="l">Properties</div></div>
        <div><div class="n">${s.shapes}</div><div class="l">Shapes</div></div>
        <div><div class="n">${s.relationships}</div><div class="l">Relationships</div></div>
        <div><div class="n">${s.decisions}</div><div class="l">Decisions</div></div>
        <div><div class="n">${s.formalCQs}+${s.backlogCQs}</div><div class="l">Questions</div></div>
      </div>
      <h2 class="sec">Modules</h2>
      <div class="grid">${mods}</div>
      <h2 class="sec">How to read this</h2>
      <div class="card">
        <p style="margin:0 0 .6rem"><b>OWL defines meaning; SHACL is the data contract.</b>
        Shared properties deliberately carry no <code>rdfs:domain</code> or <code>rdfs:range</code>,
        because under OWL a domain axiom infers a (wrong) type rather than rejecting bad data.
        Typing and cardinality live in the shapes, where a breach is a report.</p>
        <p style="margin:0 0 .6rem"><b>That is why relationships come from SHACL.</b>
        The <a href="#/relationships">relationship graph</a> is derived from shape constraints
        that name a target class — the only place typed relationships are actually stated.</p>
        <p style="margin:0"><b>Questions come before terms.</b> A term with no competency
        question behind it is scope creep, so each term links to the
        <a href="#/decisions">decision</a> that justified it.</p>
      </div>`;
  }

  function viewTerm(curie) {
    const t = byCurie.get(curie);
    if (!t) return `<div class="card err"><b>Unknown term</b><p>No term named <code>${esc(curie)}</code>.</p></div>`;

    const decisions = (t.decisions || []).map((id) => decById.get(id)).filter(Boolean);
    const whyHtml = decisions.length ? decisions.map((d) => `
      <div class="why">
        <div class="whyhead">
          <span class="did">${esc(d.id)}</span>
          <span class="wtitle">${esc(d.title)}</span>
          ${d.invariant ? '<span class="pill inv">invariant</span>' : ""}
          <span class="pill draft">${esc(d.area)}</span>
        </div>
        <p>${esc(d.reasoning)}</p>
        ${(d.rejected || []).length ? `<div class="rej">
          <div class="rejlabel">Rejected alternatives</div>
          <ul>${d.rejected.map((r) => `<li>${esc(r)}</li>`).join("")}</ul>
        </div>` : ""}
        ${d.termCuries.length > 1 ? `<div class="rej"><div class="rejlabel">Also justifies</div>
          <div class="chips" style="margin-top:.35rem">${
            d.termCuries.filter((c) => c !== curie).map((c) => link(c)).join("")}</div></div>` : ""}
      </div>`).join("")
      : `<div class="norationale">No decision record references this term yet. Per the project's
         governance, a term should have a competency question and a recorded rationale before it
         is promoted beyond <code>draft</code> — add it to <code>docs/decisions.json</code>.</div>`;

    const cons = (t.constraints || []);
    const consHtml = cons.length ? cons.map((c) => {
      if (c.kind === "sparql") {
        return `<div class="cons ${c.severity === "Warning" ? "warn" : ""}">
          <div class="chead"><span class="cpath">SPARQL constraint</span>
            <span class="pill sparql">SPARQL</span>${sevPill(c.severity)}</div>
          <blockquote>${esc(c.message)}</blockquote>
          <details><summary>Show query</summary><pre class="sparql">${esc(c.select)}</pre></details>
        </div>`;
      }
      const bits = [];
      if (c.minCount != null || c.maxCount != null) {
        bits.push(`cardinality ${c.minCount != null ? c.minCount : 0}..${c.maxCount != null ? c.maxCount : "*"}`);
      }
      if (c.class) bits.push(`class ${c.class}`);
      if (c.datatype) bits.push(`datatype ${c.datatype}`);
      if (c.in && c.in.length) bits.push(`one of ${c.in.map((v) => `"${v}"`).join(", ")}`);
      if (c.minInclusive != null) bits.push(`≥ ${c.minInclusive}`);
      if (c.maxInclusive != null) bits.push(`≤ ${c.maxInclusive}`);
      return `<div class="cons ${c.severity === "Warning" ? "warn" : ""}">
        <div class="chead"><span class="cpath">${c.path ? link(c.path) : "—"}</span>
          ${sevPill(c.severity)}<span class="card-detail">${esc(bits.join(" · "))}</span></div>
        ${c.message ? `<blockquote>${esc(c.message)}</blockquote>` : ""}
      </div>`;
    }).join("") : `<div class="norationale">No SHACL shape targets this term.</div>`;

    const relRows = [
      ...(t.outgoing || []).map((e) => ({ ...e, dir: "out" })),
      ...(t.incoming || []).map((e) => ({ ...e, dir: "in" })),
      ...(t.usedBy || []).map((e) => ({ ...e, dir: "uses" })),
    ];
    const relHtml = relRows.length ? `<div class="tablewrap"><table class="data">
      <tr><th>From</th><th>Property</th><th>To</th><th>Cardinality</th></tr>
      ${relRows.map((e) => `<tr>
        <td>${link(e.from)}</td>
        <td>${link(e.property)}</td>
        <td>${link(e.to)}</td>
        <td>${esc(e.cardinality || "—")}</td></tr>`).join("")}
    </table></div>` : `<div class="norationale">No typed relationships recorded in the shapes.</div>`;

    const vocabHtml = (t.vocabulary || []).length ? `<div class="vocab">${
      t.vocabulary.map((v) => `<span class="v"><b>${esc(v.label)}</b>${
        v.notation ? ` <span class="note">${esc(v.notation)}</span>` : ""}${
        v.rank ? ` <span class="note">rank ${esc(v.rank)}</span>` : ""}</span>`).join("")}</div>
      ${t.vocabulary.some((v) => v.note) ? t.vocabulary.filter((v) => v.note).map((v) =>
        `<p class="lede" style="font-size:.86rem;margin-top:.6rem"><b>${esc(v.label)}:</b> ${esc(v.note)}</p>`).join("") : ""}` : "";

    const hierarchy = [];
    if (t.subClassOf.length) hierarchy.push(`<div><b>Subclass of</b> <span class="chips">${t.subClassOf.map((c) => link(c)).join("")}</span></div>`);
    if (t.subPropertyOf.length) hierarchy.push(`<div><b>Subproperty of</b> <span class="chips">${t.subPropertyOf.map((c) => link(c)).join("")}</span></div>`);
    if (t.subClasses.length) hierarchy.push(`<div><b>Subclasses</b> <span class="chips">${t.subClasses.map((c) => link(c)).join("")}</span></div>`);
    if (t.disjointWith.length) hierarchy.push(`<div><b>Disjoint with</b> <span class="chips">${t.disjointWith.map((c) => link(c)).join("")}</span></div>`);

    return `
      <div class="crumb"><a href="#/">Ontology</a> ›
        <a href="#/module/${esc(t.module)}">${esc(t.module)}</a> › ${esc(t.name)}</div>
      <h1 class="title">${esc(t.name)} <span class="kindtag">${tag(t.module)}</span></h1>
      <div class="chips" style="margin:.5rem 0 .8rem">
        <span class="static">${esc(t.curie)}</span>
        <span class="pill draft">${esc(kindLabel[t.kind] || t.kind)}</span>
        <span class="pill draft">${esc(t.status)}</span>
        ${(t.altLabels || []).map((a) => `<span class="static">${esc(a)}</span>`).join("")}
      </div>
      ${t.definition ? `<p class="lede">${esc(t.definition)}</p>` : ""}
      ${t.editorialNote ? `<div class="card" style="margin-top:1rem"><b style="font-size:.8rem;letter-spacing:.08em;text-transform:uppercase;color:var(--ink-3)">Editorial note</b><p style="margin:.4rem 0 0;font-size:.92rem;color:var(--ink-2)">${esc(t.editorialNote)}</p></div>` : ""}

      <h2 class="sec">Why this exists</h2>
      ${whyHtml}

      ${hierarchy.length ? `<h2 class="sec">Hierarchy</h2>
        <div class="card" style="display:flex;flex-direction:column;gap:.55rem">${hierarchy.join("")}</div>` : ""}

      ${vocabHtml ? `<h2 class="sec">Vocabulary members</h2>${vocabHtml}` : ""}

      <h2 class="sec">Constraints${t.shapes.length ? ` · ${t.shapes.map((s) => `<code>${esc(s)}</code>`).join(" ")}` : ""}</h2>
      ${consHtml}

      <h2 class="sec">Relationships</h2>
      ${relHtml}

      <footer class="pagefoot">
        <code>${esc(t.iri)}</code>
      </footer>`;
  }

  function viewModule(name) {
    const m = DB.modules.find((x) => x.name === name);
    if (!m) return `<div class="card err"><b>Unknown module</b> <code>${esc(name)}</code></div>`;
    const terms = DB.terms.filter((t) => t.module === name);
    const shapes = DB.shapes.filter((s) => s.module === name);
    const vocabs = DB.vocabularies.filter((v) => v.module === name);
    const group = (kind, label) => {
      const items = terms.filter((t) => t.kind === kind);
      if (!items.length) return "";
      return `<h2 class="sec">${label} · ${items.length}</h2>
        <div class="tablewrap"><table class="data">
        <tr><th>Term</th><th>Definition</th><th>Why</th></tr>
        ${items.map((t) => `<tr>
          <td>${link(t.curie)}</td>
          <td>${esc((t.definition || "").split(". ")[0] || "—")}${(t.definition || "").includes(". ") ? "." : ""}</td>
          <td>${(t.decisions || []).map((d) => `<a href="#/decisions?q=${esc(d)}"><code>${esc(d)}</code></a>`).join(" ") || '<span style="color:var(--ink-3)">—</span>'}</td>
        </tr>`).join("")}
        </table></div>`;
    };
    return `
      <div class="crumb"><a href="#/">Ontology</a> › ${esc(name)}</div>
      <h1 class="title">${esc(m.title)}</h1>
      <div class="chips" style="margin:.5rem 0 .8rem">
        <span class="static">${esc(m.prefix)}:</span>
        <span class="pill draft">v${esc(m.version)}</span>
        ${m.imports.map((i) => `<a href="#/module/${esc(i)}">imports ${esc(i)}</a>`).join("")}
      </div>
      <p class="lede">${esc(m.description)}</p>
      <div class="stats">
        <div><div class="n">${terms.filter((t) => t.kind === "class").length}</div><div class="l">Classes</div></div>
        <div><div class="n">${terms.filter((t) => t.kind !== "class").length}</div><div class="l">Properties</div></div>
        <div><div class="n">${shapes.length}</div><div class="l">Shapes</div></div>
        <div><div class="n">${vocabs.length}</div><div class="l">Vocabularies</div></div>
      </div>
      ${group("class", "Classes")}
      ${group("objectProperty", "Object properties")}
      ${group("datatypeProperty", "Datatype properties")}
      ${vocabs.length ? `<h2 class="sec">Controlled vocabularies</h2>${vocabs.map((v) => `
        <div class="card"><b>${esc(v.title)}</b>
        ${v.note ? `<p style="margin:.35rem 0 .5rem;font-size:.88rem;color:var(--ink-2)">${esc(v.note)}</p>` : ""}
        <div class="vocab" style="margin-top:.5rem">${v.members.map((mm) =>
          `<span class="v"><b>${esc(mm.label)}</b>${mm.notation ? ` <span class="note">${esc(mm.notation)}</span>` : ""}</span>`).join("")}</div>
        </div>`).join("")}` : ""}`;
  }

  function viewShapes(q) {
    const query = (q || "").toLowerCase();
    let shapes = DB.shapes;
    if (query) {
      shapes = shapes.filter((s) =>
        s.name.toLowerCase().includes(query) ||
        (s.targetClass || "").toLowerCase().includes(query) ||
        s.constraints.some((c) => (c.message || "").toLowerCase().includes(query)));
    }
    const cards = shapes.map((s) => `
      <div class="card">
        <div class="mh" style="display:flex;gap:9px;align-items:baseline;flex-wrap:wrap;margin-bottom:.5rem">
          <b class="mono">${esc(s.name)}</b>
          ${s.targetClass ? link(s.targetClass) : ""}
          ${tag(s.module)}
          ${s.violations ? `<span class="pill violation">${s.violations} violation${s.violations > 1 ? "s" : ""}</span>` : ""}
          ${s.warnings ? `<span class="pill warning">${s.warnings} warning${s.warnings > 1 ? "s" : ""}</span>` : ""}
        </div>
        ${s.constraints.map((c) => `
          <div class="cons ${c.severity === "Warning" ? "warn" : ""}" style="margin-bottom:8px">
            <div class="chead">
              <span class="cpath">${c.kind === "sparql" ? "SPARQL" : (c.path ? esc(c.path) : "—")}</span>
              ${c.kind === "sparql" ? '<span class="pill sparql">SPARQL</span>' : ""}
              ${sevPill(c.severity)}
            </div>
            ${c.message ? `<blockquote>${esc(c.message)}</blockquote>` : ""}
            ${c.kind === "sparql" ? `<details><summary>Show query</summary><pre class="sparql">${esc(c.select)}</pre></details>` : ""}
          </div>`).join("")}
      </div>`).join("");
    return `
      <div class="crumb"><a href="#/">Ontology</a> › Constraints</div>
      <h1 class="title">The SHACL contract</h1>
      <p class="lede">${DB.stats.shapes} shapes carrying ${DB.stats.violations} violation-level and
      ${DB.stats.warnings} warning-level constraints. A violation is rejected at ingestion; a warning
      is admitted but routed to the stewardship queue. Every violation here has a deliberately broken
      instance in the negative test corpus — an invariant that cannot demonstrably fire does not count.</p>
      ${query ? `<p class="lede"><b>Filtered by “${esc(q)}”</b> — ${shapes.length} of ${DB.shapes.length}.
        <a href="#/shapes">Clear</a></p>` : ""}
      <h2 class="sec">Shapes</h2>
      ${cards || '<div class="norationale">No shapes match.</div>'}`;
  }

  function viewRelationships() {
    const rows = DB.relationships.map((e) => `<tr>
      <td>${link(e.from)}</td>
      <td>${link(e.property)}</td>
      <td>${link(e.to)}</td>
      <td>${esc(e.cardinality || "—")}</td>
      <td>${sevPill(e.severity)}</td></tr>`).join("");
    return `
      <div class="crumb"><a href="#/">Ontology</a> › Relationships</div>
      <h1 class="title">Relationship graph</h1>
      <p class="lede">Typed edges between classes, derived from the SHACL shapes rather than from OWL.
      The ontology deliberately keeps <code>rdfs:domain</code> and <code>rdfs:range</code> off shared
      properties — under OWL semantics a domain axiom infers a type instead of rejecting bad data —
      so the shapes are the only place typed relationships are actually stated.</p>
      <h2 class="sec">${DB.relationships.length} edges</h2>
      <div class="tablewrap"><table class="data">
        <tr><th>Subject class</th><th>Property</th><th>Object class</th><th>Cardinality</th><th>Severity</th></tr>
        ${rows}
      </table></div>`;
  }

  function viewDecisions(q) {
    const query = (q || "").toLowerCase();
    let ds = DB.decisions;
    if (query) {
      ds = ds.filter((d) =>
        d.id.toLowerCase().includes(query) ||
        d.title.toLowerCase().includes(query) ||
        d.reasoning.toLowerCase().includes(query) ||
        (d.area || "").toLowerCase().includes(query));
    }
    const areas = [];
    for (const d of ds) if (!areas.includes(d.area)) areas.push(d.area);
    const body = areas.map((area) => `
      <h2 class="sec">${esc(area)}</h2>
      ${ds.filter((d) => d.area === area).map((d) => `
        <div class="why" id="${esc(d.id)}">
          <div class="whyhead">
            <span class="did">${esc(d.id)}</span>
            <span class="wtitle">${esc(d.title)}</span>
            ${d.invariant ? '<span class="pill inv">invariant</span>' : ""}
          </div>
          <p>${esc(d.reasoning)}</p>
          ${(d.rejected || []).length ? `<div class="rej">
            <div class="rejlabel">Rejected alternatives</div>
            <ul>${d.rejected.map((r) => `<li>${esc(r)}</li>`).join("")}</ul></div>` : ""}
          ${d.termCuries.length ? `<div class="rej"><div class="rejlabel">Terms</div>
            <div class="chips" style="margin-top:.35rem">${d.termCuries.map((c) => link(c)).join("")}</div></div>` : ""}
        </div>`).join("")}`).join("");
    return `
      <div class="crumb"><a href="#/">Ontology</a> › Decisions</div>
      <h1 class="title">Decision register</h1>
      <p class="lede">Why the ontology is shaped the way it is: ${DB.decisions.length} decisions with the
      reasoning that survived challenge, and the alternatives that were rejected — recorded so they stay
      rejected for the recorded reason. Each term page links to the decisions that justify it.</p>
      ${query ? `<p class="lede"><b>Filtered by “${esc(q)}”</b> — ${ds.length} of ${DB.decisions.length}.
        <a href="#/decisions">Clear</a></p>` : ""}
      ${body || '<div class="norationale">No decisions match.</div>'}`;
  }

  function viewQuestions(q) {
    const query = (q || "").toLowerCase();
    const cq = DB.competencyQuestions;
    const formal = query
      ? cq.formal.filter((x) => (x.id + " " + x.question).toLowerCase().includes(query))
      : cq.formal;
    const backlog = query
      ? cq.backlog.filter((x) => (x.question + " " + x.section).toLowerCase().includes(query))
      : cq.backlog;
    const sections = [];
    for (const b of backlog) if (!sections.includes(b.section)) sections.push(b.section);
    return `
      <div class="crumb"><a href="#/">Ontology</a> › Questions</div>
      <h1 class="title">Competency questions</h1>
      <p class="lede">Questions come before terms: a term with no question behind it is scope creep.
      The formalized ones exist as SPARQL executed by CI against seed data; the backlog is queued
      vocabulary work, grouped by the design area it will force into being.</p>
      ${query ? `<p class="lede"><b>Filtered by “${esc(q)}”</b>. <a href="#/questions">Clear</a></p>` : ""}
      <h2 class="sec">Formalized · executed by CI</h2>
      ${formal.map((f) => `<div class="card">
        <div style="display:flex;gap:9px;align-items:baseline;flex-wrap:wrap">
          <b class="mono">${esc(f.id)}</b>
          <span>${esc(f.question)}</span>
        </div>
        <div class="chips" style="margin-top:.5rem">${f.modules.map((m) => tag(m)).join("")}</div>
        ${f.sparql ? `<details style="margin-top:.55rem"><summary style="font-size:.78rem;color:var(--accent-ink);cursor:pointer;font-weight:600">Show query · ${esc(f.query)}</summary>
          <pre class="sparql">${esc(f.sparql)}</pre></details>` : ""}
      </div>`).join("") || '<div class="norationale">No formalized questions match.</div>'}
      ${sections.map((s) => `
        <h2 class="sec">Backlog · ${esc(s)}</h2>
        <div class="card"><ul style="margin:0;padding-left:1.1rem">
          ${backlog.filter((b) => b.section === s).map((b) =>
            `<li style="margin-bottom:.4rem">${esc(b.question)}</li>`).join("")}
        </ul></div>`).join("")}`;
  }

  /* ---------- router ---------- */
  function route() {
    const raw = location.hash.replace(/^#/, "") || "/";
    const [path, qs] = raw.split("?");
    const params = new URLSearchParams(qs || "");
    const q = params.get("q") || "";
    const parts = path.split("/").filter(Boolean);
    const main = $("#main");
    let html;
    if (!parts.length) html = viewHome();
    else if (parts[0] === "term") html = viewTerm(decodeURIComponent(parts[1] || ""));
    else if (parts[0] === "module") html = viewModule(decodeURIComponent(parts[1] || ""));
    else if (parts[0] === "shapes") html = viewShapes(q);
    else if (parts[0] === "relationships") html = viewRelationships();
    else if (parts[0] === "decisions") html = viewDecisions(q);
    else if (parts[0] === "questions") html = viewQuestions(q);
    else html = `<div class="card err"><b>Not found</b><p>Nothing at <code>${esc(path)}</code>. <a href="#/">Start over</a>.</p></div>`;
    main.innerHTML = html;
    main.scrollTop = 0;
    window.scrollTo({ top: 0, behavior: "instant" in window ? "instant" : "auto" });
    document.title = (parts.length ? decodeURIComponent(parts[1] || parts[0]) + " · " : "") + "Platform Ontology Browser";
    markActive();
  }

  /* ---------- wiring ---------- */
  function wire() {
    const searchEl = $("#search");
    const results = $("#results");
    let selIdx = -1;

    searchEl.addEventListener("input", () => { selIdx = -1; renderResults(searchEl.value); });
    searchEl.addEventListener("focus", () => { if (searchEl.value) renderResults(searchEl.value); });
    searchEl.addEventListener("keydown", (e) => {
      const items = [...results.querySelectorAll("a")];
      if (e.key === "ArrowDown" || e.key === "ArrowUp") {
        e.preventDefault();
        if (!items.length) return;
        selIdx = e.key === "ArrowDown"
          ? Math.min(selIdx + 1, items.length - 1)
          : Math.max(selIdx - 1, 0);
        items.forEach((a, i) => a.classList.toggle("sel", i === selIdx));
        items[selIdx].scrollIntoView({ block: "nearest" });
      } else if (e.key === "Enter") {
        if (selIdx >= 0 && items[selIdx]) { location.hash = items[selIdx].getAttribute("href"); }
        else if (items[0]) { location.hash = items[0].getAttribute("href"); }
        searchEl.blur(); results.hidden = true;
      } else if (e.key === "Escape") {
        searchEl.value = ""; results.hidden = true; searchEl.blur();
      }
    });
    results.addEventListener("click", (e) => {
      if (e.target.closest("a")) { results.hidden = true; searchEl.value = ""; }
    });
    document.addEventListener("click", (e) => {
      if (!e.target.closest(".searchwrap")) results.hidden = true;
    });
    document.addEventListener("keydown", (e) => {
      const typing = /^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement.tagName);
      if (e.key === "/" && !typing) { e.preventDefault(); searchEl.focus(); }
      if ((e.key === "k" || e.key === "K") && (e.metaKey || e.ctrlKey)) { e.preventDefault(); searchEl.focus(); }
    });

    $("#filter").addEventListener("input", renderTree);
    document.querySelectorAll(".kindtabs button").forEach((b) => {
      b.addEventListener("click", () => {
        sideKind = b.dataset.kind;
        document.querySelectorAll(".kindtabs button").forEach((x) => {
          x.classList.toggle("on", x === b);
          x.setAttribute("aria-selected", String(x === b));
        });
        renderTree();
      });
    });

    const themeBtn = $("#themeBtn");
    const stored = (() => { try { return localStorage.getItem("ont-theme"); } catch { return null; } })();
    if (stored) document.documentElement.setAttribute("data-theme", stored);
    themeBtn.addEventListener("click", () => {
      const cur = document.documentElement.getAttribute("data-theme");
      const isDark = cur ? cur === "dark"
        : window.matchMedia("(prefers-color-scheme: dark)").matches;
      const next = isDark ? "light" : "dark";
      document.documentElement.setAttribute("data-theme", next);
      try { localStorage.setItem("ont-theme", next); } catch { /* private mode */ }
    });

    window.addEventListener("hashchange", route);
  }

  /* ---------- boot ---------- */
  fetch("data/index.json")
    .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
    .then((data) => {
      DB = data;
      DB.terms.forEach((t) => byCurie.set(t.curie, t));
      DB.decisions.forEach((d) => decById.set(d.id, d));
      buildSearchDocs();
      wire();
      renderTree();
      route();
    })
    .catch((err) => {
      $("#main").innerHTML = `<div class="card err">
        <b>Could not load the ontology index</b>
        <p style="color:var(--ink-2)">${esc(err.message)}. The index is generated by
        <code>ci/build_index.py</code> into <code>browser/data/index.json</code>; run it, and
        serve this directory over HTTP rather than opening the file directly
        (<code>python3 -m http.server</code>).</p></div>`;
    });
})();
